apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordination-monitor
  labels:
    app: coordination-monitor
    version: v4.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coordination-monitor
  template:
    metadata:
      labels:
        app: coordination-monitor
        version: v4.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: coordination
        image: cert-framework/coordination:4.0.0
        ports:
        - containerPort: 8000
          name: api
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        env:
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: anthropic-secret
              key: api-key
        - name: LOG_LEVEL
          value: "INFO"
        - name: LOG_FORMAT
          value: "json"
        - name: METRICS_ENABLED
          value: "true"
        - name: MAX_COST_PER_HOUR
          value: "10.0"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: coordination-monitor
  labels:
    app: coordination-monitor
spec:
  type: LoadBalancer
  selector:
    app: coordination-monitor
  ports:
  - name: api
    port: 80
    targetPort: 8000
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
---
apiVersion: v1
kind: Secret
metadata:
  name: anthropic-secret
type: Opaque
stringData:
  api-key: "YOUR_ANTHROPIC_API_KEY_HERE"
