'use client';

import { useState } from 'react';
import Card from '@/components/Card';
import { ChevronDown, ChevronRight, CheckCircle, FileText, Upload, Play, Download, AlertCircle, Info, Globe, MessageCircle } from 'lucide-react';
import { cn } from '@/lib/utils';
import { typographyClasses } from '@/theme/typography';

interface Section {
  id: string;
  title: string;
  icon: any;
  content: {
    overview: string;
    steps: { title: string; description: string; }[];
    tips?: string[];
    videoUrl?: string;
  };
}

const HELP_SECTIONS: Section[] = [
  {
    id: 'getting-started',
    title: 'Getting Started',
    icon: Info,
    content: {
      overview: 'CERT Dashboard helps you comply with EU AI Act requirements without writing code. This guide will walk you through the three main features.',
      steps: [
        {
          title: 'What You Need',
          description: 'Before starting, you\'ll need: 1) Information about your AI system, 2) Production traces from your system (JSONL file), and 3) About 15-30 minutes of your time.'
        },
        {
          title: 'Choose Your Starting Point',
          description: 'Not sure where to start? Use the Risk Assessment first to understand your compliance requirements, then generate documents, and finally run audits.'
        }
      ],
      tips: [
        'Start with the Risk Assessment if you\'re new to EU AI Act compliance',
        'Keep your traces file handy - you\'ll need it for document generation and audits',
        'All your data stays private - nothing is sent to external servers'
      ]
    }
  },
  {
    id: 'risk-assessment',
    title: 'Risk Assessment Wizard',
    icon: CheckCircle,
    content: {
      overview: 'Determine if your AI system is high-risk, limited-risk, or minimal-risk according to EU AI Act Annex III. Get a professional PDF report with recommendations.',
      steps: [
        {
          title: 'Step 1: Navigate to Assessment',
          description: 'Click "Assessment" in the sidebar menu to open the Risk Assessment Wizard.'
        },
        {
          title: 'Step 2: Answer 10 Questions',
          description: 'You\'ll see 10 questions divided into two parts: Risk Classification (5 questions about your system\'s use case) and Readiness Assessment (5 questions about your organization).'
        },
        {
          title: 'Step 3: Review Your Results',
          description: 'After completing the questionnaire, you\'ll see your risk level (PROHIBITED, HIGH_RISK, LIMITED_RISK, or MINIMAL_RISK), readiness score (0-100%), and estimated cost & timeline for compliance.'
        },
        {
          title: 'Step 4: Download PDF Report',
          description: 'Enter your email address and click "Download Report" to receive a professional PDF you can share with stakeholders or consultants.'
        }
      ],
      tips: [
        'Answer honestly - this assessment helps you plan properly',
        'If you\'re unsure about a question, choose the most conservative answer',
        'The readiness score shows your current compliance maturity',
        'Save the PDF report for your records and future reference'
      ]
    }
  },
  {
    id: 'document-generation',
    title: 'Document Generator',
    icon: FileText,
    content: {
      overview: 'Auto-generate EU AI Act compliance documents from your production traces. The system creates Word documents that are 70% complete - you just need to fill in expert sections.',
      steps: [
        {
          title: 'Step 1: Prepare Your Traces File',
          description: 'You need a JSONL file containing your system\'s production traces. This file is generated by the CERT monitoring framework when you instrument your application. Each line should be a JSON object with trace data.'
        },
        {
          title: 'Step 2: Upload Traces',
          description: 'Go to the "Generate" page and drag-and-drop your traces file (or click to browse). The system accepts .jsonl and .json files.'
        },
        {
          title: 'Step 3: Enter System Information',
          description: 'Fill in: System Name (required), Version (optional), Provider Name (required - your company), and Intended Purpose (optional but recommended).'
        },
        {
          title: 'Step 4: Select Documents',
          description: 'Choose which documents to generate. Two are required: Risk Classification Report and Annex IV Technical Documentation. Three are optional: Article 15 Report, Audit Trail Guide, and Monitoring Framework.'
        },
        {
          title: 'Step 5: Generate & Download',
          description: 'Click "Generate Documents" and wait 10-30 seconds. Download the ZIP file containing all Word documents.'
        },
        {
          title: 'Step 6: Complete Expert Sections',
          description: 'Open each Word document and search for [EXPERT INPUT REQUIRED]. Fill in these sections with your domain expertise (estimated 8-10 hours total).'
        }
      ],
      tips: [
        'More traces = better metrics. Aim for at least 100 traces for meaningful data',
        'The system auto-fills metrics like error rates, latency, and request counts',
        'Save frequently while completing expert sections',
        'Export to PDF once complete for formal submission'
      ]
    }
  },
  {
    id: 'compliance-audit',
    title: 'Compliance Audit',
    icon: Play,
    content: {
      overview: 'Run automated accuracy audits to check if your system meets EU AI Act Article 15 requirements. Get detailed pass/fail results in 30-120 seconds.',
      steps: [
        {
          title: 'Step 1: Upload Traces',
          description: 'Navigate to the "Audit" page and upload your traces file (same JSONL file used for document generation).'
        },
        {
          title: 'Step 2: Choose Evaluator Type',
          description: 'Select between Semantic (uses AI embeddings - recommended for most cases) or Exact Match (requires exact text matches - use for financial/legal domains).'
        },
        {
          title: 'Step 3: Set Threshold',
          description: 'Adjust the accuracy threshold using the slider. Default is 70%, but EU AI Act Article 15 typically requires 90% for compliance.'
        },
        {
          title: 'Step 4: Run Audit',
          description: 'Click "Run Compliance Audit" and wait 30-120 seconds depending on the number of traces.'
        },
        {
          title: 'Step 5: Review Results',
          description: 'You\'ll see: Overall pass rate, total/passed/failed traces, compliance status (✓ COMPLIANT if ≥90%), and a table of failed traces with reasons.'
        },
        {
          title: 'Step 6: Download Report',
          description: 'Click "Download Report" to save a JSON file with complete audit results for your records.'
        }
      ],
      tips: [
        'Semantic evaluator is 10x faster than exact match for large trace files',
        'Failed traces show why they failed - use this to improve your system',
        'Run audits regularly (weekly/monthly) to monitor accuracy over time',
        'A pass rate <90% means you need to investigate and fix issues'
      ]
    }
  },
  {
    id: 'traces-file',
    title: 'Understanding Traces Files',
    icon: Upload,
    content: {
      overview: 'Traces files contain records of your AI system\'s inputs, outputs, and metadata. They\'re essential for document generation and audits.',
      steps: [
        {
          title: 'What is a Traces File?',
          description: 'A traces file is a JSONL (JSON Lines) file where each line is a JSON object representing one request/response from your AI system. It includes: timestamp, input query, output answer, context used, token counts, cost, and performance metrics.'
        },
        {
          title: 'How to Generate Traces',
          description: 'Install CERT framework in your application: pip install cert-framework. Add one line to your code: from cert.integrations.auto import *. Run your application normally. Traces are automatically saved to cert_traces.jsonl.'
        },
        {
          title: 'Trace File Format',
          description: 'Each trace should have: timestamp (ISO 8601), input_query (user request), answer (system response), context (optional - RAG context), status (success/error), duration_ms, tokens (input/output), cost (optional).'
        },
        {
          title: 'Example Trace',
          description: '{"timestamp": "2025-01-15T10:30:00Z", "input_query": "What is the capital of France?", "answer": "Paris is the capital of France.", "context": "France is a country in Europe...", "status": "success", "duration_ms": 245, "tokens": {"input": 15, "output": 8}, "cost": 0.002}'
        }
      ],
      tips: [
        'Keep traces for at least 30 days for meaningful compliance analysis',
        'Each trace represents one API call or user interaction',
        'More detailed traces = better compliance documentation',
        'Clean PII (personal information) from traces before generating documents'
      ]
    }
  },
  {
    id: 'troubleshooting',
    title: 'Troubleshooting',
    icon: AlertCircle,
    content: {
      overview: 'Common issues and how to solve them.',
      steps: [
        {
          title: 'Error: "Missing traces data"',
          description: 'Solution: Make sure your JSONL file is properly formatted. Each line must be valid JSON. Test with a small file (10-20 traces) first.'
        },
        {
          title: 'Error: "PDF generation failed"',
          description: 'Solution: This usually means Python dependencies are missing on the server. Contact your administrator or try downloading JSON results instead.'
        },
        {
          title: 'Error: "Audit execution failed"',
          description: 'Solution: Check that your traces have the required fields: input_query, answer, and timestamp. Make sure the file isn\'t corrupted.'
        },
        {
          title: 'Documents are incomplete',
          description: 'Solution: This is normal! Documents contain [EXPERT INPUT REQUIRED] sections that need manual completion. Search for this text in Word and fill in your expertise.'
        },
        {
          title: 'Audit shows low accuracy (<70%)',
          description: 'Solution: Review the failed traces table to understand why traces are failing. Common issues: hallucinations, incomplete answers, or wrong context. Fix your prompts/RAG pipeline and re-run.'
        },
        {
          title: 'Upload is slow',
          description: 'Solution: Large trace files (>10MB) take time to upload and process. Be patient or split into smaller batches. For audits, 1000-5000 traces is usually sufficient.'
        }
      ],
      tips: [
        'Always test with a small sample file first (10-20 traces)',
        'Check browser console (F12) for detailed error messages',
        'Keep a backup of your traces file',
        'Contact support with the exact error message if stuck'
      ]
    }
  },
  {
    id: 'best-practices',
    title: 'Best Practices',
    icon: CheckCircle,
    content: {
      overview: 'Tips for getting the most out of CERT Dashboard.',
      steps: [
        {
          title: '1. Start with Assessment',
          description: 'Always begin with the Risk Assessment to understand your compliance obligations before generating documents or running audits.'
        },
        {
          title: '2. Collect Sufficient Traces',
          description: 'Aim for at least 100 production traces for meaningful metrics. More traces = more accurate compliance reports. Ideal: 1000-10000 traces covering 30+ days.'
        },
        {
          title: '3. Regular Audits',
          description: 'Run compliance audits weekly or monthly to catch accuracy issues early. Don\'t wait until annual review time.'
        },
        {
          title: '4. Version Control Documents',
          description: 'Keep versioned copies of generated documents with dates. Track changes as your system evolves.'
        },
        {
          title: '5. Involve Experts Early',
          description: 'Share assessment results with legal/compliance experts early. The [EXPERT INPUT REQUIRED] sections need domain expertise.'
        },
        {
          title: '6. Clean Your Data',
          description: 'Remove PII (personal information) from traces before uploading. The dashboard doesn\'t do this automatically.'
        }
      ],
      tips: [
        'Document your entire compliance workflow - not just the outputs',
        'Run a full audit before major releases or regulatory reviews',
        'Keep stakeholders informed with PDF assessment reports',
        'Budget 8-10 hours for expert review of generated documents'
      ]
    }
  }
];

export default function HelpPage() {
  const [expandedSection, setExpandedSection] = useState<string>('getting-started');

  const toggleSection = (sectionId: string) => {
    setExpandedSection(expandedSection === sectionId ? '' : sectionId);
  };

  return (
    <div className="min-h-screen p-6">
      <div className="max-w-5xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <h1 className={cn(typographyClasses.pageTitle, "mb-2")}>
            Help & Documentation
          </h1>
          <p className={typographyClasses.body}>
            Learn how to use CERT Dashboard for EU AI Act compliance
          </p>
        </div>

        {/* Quick Links */}
        <Card className="mb-6 bg-blue-50 dark:bg-blue-900/20 border-blue-200 dark:border-blue-800">
          <div className="flex items-start gap-3">
            <Info size={24} className="text-blue-600 dark:text-blue-400 flex-shrink-0 mt-1" />
            <div>
              <h3 className={cn(typographyClasses.subsectionTitle, "text-blue-900 dark:text-blue-100 mb-2")}>
                Quick Start Guide
              </h3>
              <p className={cn(typographyClasses.body, "text-blue-800 dark:text-blue-200 mb-3")}>
                New to CERT Dashboard? Follow these steps:
              </p>
              <ol className={cn(typographyClasses.body, "text-blue-800 dark:text-blue-200 space-y-1")}>
                <li><strong>1. Risk Assessment</strong> → Understand your compliance requirements</li>
                <li><strong>2. Document Generation</strong> → Create compliance documents from traces</li>
                <li><strong>3. Compliance Audit</strong> → Check accuracy and compliance status</li>
              </ol>
            </div>
          </div>
        </Card>

        {/* Help Sections */}
        <div className="space-y-4">
          {HELP_SECTIONS.map((section) => {
            const Icon = section.icon;
            const isExpanded = expandedSection === section.id;

            return (
              <Card key={section.id} className="overflow-hidden">
                <div
                  onClick={() => toggleSection(section.id)}
                  className="flex items-center justify-between cursor-pointer p-6 hover:bg-zinc-50 dark:hover:bg-zinc-800/50 transition-colors"
                >
                  <div className="flex items-center gap-3">
                    <div className="p-2 bg-blue-100 dark:bg-blue-900/30 rounded-lg">
                      <Icon size={24} className="text-blue-600 dark:text-blue-400" />
                    </div>
                    <h2 className={typographyClasses.sectionTitle}>
                      {section.title}
                    </h2>
                  </div>
                  {isExpanded ? (
                    <ChevronDown size={24} className="text-zinc-400" />
                  ) : (
                    <ChevronRight size={24} className="text-zinc-400" />
                  )}
                </div>

                {isExpanded && (
                  <div className="px-6 pb-6 space-y-6">
                    {/* Overview */}
                    <div className="p-4 bg-zinc-50 dark:bg-zinc-800 rounded-lg">
                      <p className={typographyClasses.body}>
                        {section.content.overview}
                      </p>
                    </div>

                    {/* Steps */}
                    <div className="space-y-4">
                      {section.content.steps.map((step, idx) => (
                        <div key={idx} className="flex gap-4">
                          <div className="flex-shrink-0 w-8 h-8 bg-blue-600 text-white rounded-full flex items-center justify-center font-bold text-sm">
                            {idx + 1}
                          </div>
                          <div className="flex-1">
                            <h3 className={cn(typographyClasses.subsectionTitle, "mb-1")}>
                              {step.title}
                            </h3>
                            <p className={typographyClasses.body}>
                              {step.description}
                            </p>
                          </div>
                        </div>
                      ))}
                    </div>

                    {/* Tips */}
                    {section.content.tips && section.content.tips.length > 0 && (
                      <div className="p-4 bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800 rounded-lg">
                        <h3 className={cn(typographyClasses.subsectionTitle, "text-green-900 dark:text-green-100 mb-2 flex items-center gap-2")}>
                          <CheckCircle size={18} />
                          Pro Tips
                        </h3>
                        <ul className={cn(typographyClasses.body, "text-green-800 dark:text-green-200 space-y-1")}>
                          {section.content.tips.map((tip, idx) => (
                            <li key={idx}>• {tip}</li>
                          ))}
                        </ul>
                      </div>
                    )}
                  </div>
                )}
              </Card>
            );
          })}
        </div>

        {/* Additional Resources */}
        <Card className="mt-8">
          <h2 className={cn(typographyClasses.sectionTitle, "mb-4")}>
            Additional Resources
          </h2>
          <div className="space-y-6">
            <div>
              <div className="flex items-center gap-2 mb-2">
                <Globe size={20} className="text-blue-600 dark:text-blue-400" />
                <h3 className={typographyClasses.subsectionTitle}>
                  External Resources
                </h3>
              </div>
              <ul className={cn(typographyClasses.body, "space-y-2")}>
                <li>• <a href="https://artificialintelligenceact.eu/" target="_blank" className="text-blue-600 dark:text-blue-400 hover:underline">EU AI Act Official Text</a></li>
                <li>• <a href="https://github.com/Javihaus/cert-framework" target="_blank" className="text-blue-600 dark:text-blue-400 hover:underline">CERT Framework GitHub</a></li>
              </ul>
            </div>

            <div>
              <div className="flex items-center gap-2 mb-2">
                <MessageCircle size={20} className="text-blue-600 dark:text-blue-400" />
                <h3 className={typographyClasses.subsectionTitle}>
                  Need More Help?
                </h3>
              </div>
              <p className={typographyClasses.body}>
                Contact: <a href="mailto:javier@jmarin.info" className="text-blue-600 dark:text-blue-400 hover:underline">javier@jmarin.info</a>
              </p>
            </div>
          </div>
        </Card>

        {/* FAQ */}
        <Card className="mt-6">
          <h2 className={cn(typographyClasses.sectionTitle, "mb-4")}>
            Frequently Asked Questions
          </h2>
          <div className="space-y-4">
            <div>
              <h3 className={cn(typographyClasses.subsectionTitle, "mb-1")}>
                Q: Is my data sent to external servers?
              </h3>
              <p className={typographyClasses.body}>
                A: No. All processing happens locally or on your infrastructure. Your traces never leave your control.
              </p>
            </div>
            <div>
              <h3 className={cn(typographyClasses.subsectionTitle, "mb-1")}>
                Q: How long does document generation take?
              </h3>
              <p className={typographyClasses.body}>
                A: Typically 10-30 seconds for 5 documents with 1000 traces. The documents are 70% complete - you need 8-10 hours for expert review.
              </p>
            </div>
            <div>
              <h3 className={cn(typographyClasses.subsectionTitle, "mb-1")}>
                Q: What's the difference between semantic and exact evaluators?
              </h3>
              <p className={typographyClasses.body}>
                A: Semantic uses AI to understand meaning (flexible, recommended). Exact requires identical text (strict, use for financial/legal).
              </p>
            </div>
            <div>
              <h3 className={cn(typographyClasses.subsectionTitle, "mb-1")}>
                Q: How many traces do I need?
              </h3>
              <p className={typographyClasses.body}>
                A: Minimum 100 for basic analysis. Recommended 1000-10000 covering 30+ days for robust compliance reporting.
              </p>
            </div>
            <div>
              <h3 className={cn(typographyClasses.subsectionTitle, "mb-1")}>
                Q: Can I use this for production compliance submissions?
              </h3>
              <p className={typographyClasses.body}>
                A: Yes, but documents require expert review. The [EXPERT INPUT REQUIRED] sections need domain expertise before submission.
              </p>
            </div>
          </div>
        </Card>
      </div>
    </div>
  );
}
