"""
Generate .docx template files with Jinja2 placeholders for docxtpl.

Run this script to create the template files that DocxReportGenerator uses.
Requires: pip install cert-framework[compliance]
"""

from pathlib import Path

try:
    from docx import Document
    from docx.shared import Inches, Pt, RGBColor
    from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
except ImportError:
    raise ImportError(
        "Template generation requires: pip install python-docx\n"
        "Or install full compliance extras: pip install cert-framework[compliance]"
    )


def create_article15_template():
    """Create Article 15 compliance report template."""
    doc = Document()

    # Title
    title = doc.add_heading('EU AI Act Article 15 Compliance Report', 0)
    title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

    # System Information Section
    doc.add_heading('1. System Information', 1)
    doc.add_paragraph(f'System Name: {{{{ system_name }}}}')
    doc.add_paragraph(f'Version: {{{{ system_version }}}}')
    doc.add_paragraph(f'Provider: {{{{ provider_name }}}}')
    doc.add_paragraph(f'Intended Purpose: {{{{ intended_purpose }}}}')
    doc.add_paragraph(f'Report Date: {{{{ report_date }}}}')
    doc.add_paragraph(f'Evaluator: {{{{ evaluator_name }}}}')

    # Performance Metrics Section
    doc.add_heading('2. Accuracy Performance Metrics', 1)
    doc.add_paragraph(f'Total Traces Collected: {{{{ total_traces }}}}')
    doc.add_paragraph(f'Traces Evaluated: {{{{ evaluated_traces }}}}')
    doc.add_paragraph(f'Traces Passed: {{{{ passed_traces }}}}')
    doc.add_paragraph(f'Traces Failed: {{{{ failed_traces_count }}}}')
    doc.add_paragraph(f'Overall Accuracy: {{{{ accuracy_percentage }}}}')
    doc.add_paragraph(f'Mean Confidence Score: {{{{ mean_confidence }}}}')
    doc.add_paragraph(f'Median Confidence Score: {{{{ median_confidence }}}}')
    doc.add_paragraph(f'Threshold Used: {{{{ threshold_used }}}}')

    # Temporal Analysis Section
    doc.add_heading('3. Temporal Analysis', 1)
    doc.add_paragraph(f'Monitoring Period: {{{{ period_start }}}} to {{{{ period_end }}}}')
    doc.add_paragraph()
    doc.add_paragraph('Daily Accuracy Trend:')

    # Table for daily accuracy
    table = doc.add_table(rows=1, cols=2)
    table.style = 'Light Grid Accent 1'
    hdr_cells = table.rows[0].cells
    hdr_cells[0].text = 'Date'
    hdr_cells[1].text = 'Accuracy'

    # Add Jinja2 loop for daily accuracy
    doc.add_paragraph('{%tr for day in daily_accuracy %}')
    row = table.add_row()
    row.cells[0].text = '{{ day.date }}'
    row.cells[1].text = '{{ day.accuracy }}'
    doc.add_paragraph('{% endtr %}')

    # Failed Traces Section
    doc.add_heading('4. Failed Trace Analysis', 1)
    doc.add_paragraph('The following traces failed accuracy evaluation (top 10 examples):')
    doc.add_paragraph()

    # Table for failed traces
    traces_table = doc.add_table(rows=1, cols=4)
    traces_table.style = 'Light Grid Accent 1'
    hdr_cells = traces_table.rows[0].cells
    hdr_cells[0].text = 'Timestamp'
    hdr_cells[1].text = 'Query'
    hdr_cells[2].text = 'Confidence'
    hdr_cells[3].text = 'Reason'

    # Add Jinja2 loop for failed traces
    doc.add_paragraph('{%tr for trace in failed_traces %}')
    row = traces_table.add_row()
    row.cells[0].text = '{{ trace.timestamp }}'
    row.cells[1].text = '{{ trace.query }}'
    row.cells[2].text = '{{ trace.confidence }}'
    row.cells[3].text = '{{ trace.reason }}'
    doc.add_paragraph('{% endtr %}')

    # Evaluation Methodology Section
    doc.add_heading('5. Evaluation Methodology', 1)
    doc.add_paragraph('{{ evaluation_methodology }}')

    # Compliance Statement Section
    doc.add_heading('6. Compliance Statement', 1)
    doc.add_paragraph('{{ compliance_statement }}')

    # Footer
    doc.add_paragraph()
    footer_para = doc.add_paragraph()
    footer_para.add_run('Generated by CERT Framework - EU AI Act Article 15 Compliance Monitor')
    footer_para.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
    footer_run = footer_para.runs[0]
    footer_run.font.size = Pt(9)
    footer_run.font.color.rgb = RGBColor(128, 128, 128)

    # Save
    template_path = Path(__file__).parent / 'Article_15_Template.docx'
    doc.save(template_path)
    print(f"✓ Created: {template_path}")
    return template_path


def create_monitoring_template():
    """Create Template 6 monitoring report."""
    doc = Document()

    # Title
    title = doc.add_heading('Production Monitoring Report (Template 6)', 0)
    title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

    # System Information Section
    doc.add_heading('1. System Information', 1)
    doc.add_paragraph(f'System Name: {{{{ system_name }}}}')
    doc.add_paragraph(f'Version: {{{{ system_version }}}}')
    doc.add_paragraph(f'Provider: {{{{ provider_name }}}}')
    doc.add_paragraph(f'Report Date: {{{{ report_date }}}}')

    # Monitoring Period Section
    doc.add_heading('2. Monitoring Period', 1)
    doc.add_paragraph(f'Period: {{{{ period_start }}}} to {{{{ period_end }}}}')

    # Trace Statistics Section
    doc.add_heading('3. Trace Statistics', 1)
    doc.add_paragraph(f'Total Traces: {{{{ total_traces }}}}')
    doc.add_paragraph(f'Average Latency: {{{{ avg_latency_ms }}}} ms')
    doc.add_paragraph(f'P50 Latency: {{{{ p50_latency_ms }}}} ms')
    doc.add_paragraph(f'P95 Latency: {{{{ p95_latency_ms }}}} ms')
    doc.add_paragraph(f'P99 Latency: {{{{ p99_latency_ms }}}} ms')
    doc.add_paragraph(f'Error Count: {{{{ error_count }}}}')
    doc.add_paragraph(f'Error Rate: {{{{ error_rate }}}}')

    # Accuracy Distribution Section
    doc.add_heading('4. Accuracy Distribution', 1)
    doc.add_paragraph('Distribution of accuracy scores across all traces:')

    # Table for accuracy distribution
    dist_table = doc.add_table(rows=1, cols=2)
    dist_table.style = 'Light Grid Accent 1'
    hdr_cells = dist_table.rows[0].cells
    hdr_cells[0].text = 'Bucket'
    hdr_cells[1].text = 'Count'

    doc.add_paragraph('{%tr for bucket in accuracy_distribution %}')
    row = dist_table.add_row()
    row.cells[0].text = '{{ bucket.bucket }}'
    row.cells[1].text = '{{ bucket.count }}'
    doc.add_paragraph('{% endtr %}')

    # Anomalies Section
    doc.add_heading('5. Detected Anomalies', 1)
    doc.add_paragraph('The following anomalies were detected during monitoring:')
    doc.add_paragraph()

    # Table for anomalies
    anomaly_table = doc.add_table(rows=1, cols=5)
    anomaly_table.style = 'Light Grid Accent 1'
    hdr_cells = anomaly_table.rows[0].cells
    hdr_cells[0].text = 'Type'
    hdr_cells[1].text = 'Description'
    hdr_cells[2].text = 'Severity'
    hdr_cells[3].text = 'Timestamp'
    hdr_cells[4].text = 'Affected Traces'

    doc.add_paragraph('{%tr for anomaly in anomalies %}')
    row = anomaly_table.add_row()
    row.cells[0].text = '{{ anomaly.type }}'
    row.cells[1].text = '{{ anomaly.description }}'
    row.cells[2].text = '{{ anomaly.severity }}'
    row.cells[3].text = '{{ anomaly.timestamp }}'
    row.cells[4].text = '{{ anomaly.affected_traces }}'
    doc.add_paragraph('{% endtr %}')

    # Recommendations Section
    doc.add_heading('6. Recommendations', 1)
    doc.add_paragraph('{%p for rec in recommendations %}')
    doc.add_paragraph('• {{ rec }}')
    doc.add_paragraph('{% endp %}')

    # Footer
    doc.add_paragraph()
    footer_para = doc.add_paragraph()
    footer_para.add_run('Generated by CERT Framework - Production Monitoring System')
    footer_para.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
    footer_run = footer_para.runs[0]
    footer_run.font.size = Pt(9)
    footer_run.font.color.rgb = RGBColor(128, 128, 128)

    # Save
    template_path = Path(__file__).parent / 'Template_6_Monitoring.docx'
    doc.save(template_path)
    print(f"✓ Created: {template_path}")
    return template_path


if __name__ == '__main__':
    print("Generating .docx template files...")
    print()
    create_article15_template()
    create_monitoring_template()
    print()
    print("Templates generated successfully!")
    print("You can now edit these files in Microsoft Word to customize formatting.")
