apiVersion: apps/v1
kind: Deployment
metadata:
  name: hamiltonian-monitor
  labels:
    app: hamiltonian-monitor
    version: v4.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hamiltonian-monitor
  template:
    metadata:
      labels:
        app: hamiltonian-monitor
        version: v4.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: hamiltonian
        image: cert-framework/hamiltonian:4.0.0
        ports:
        - containerPort: 8000
          name: api
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        env:
        - name: PRELOAD_MODELS
          value: "true"
        - name: MODEL_NAME
          value: "Qwen/Qwen2.5-7B-Instruct"
        - name: DEVICE
          value: "cuda"
        - name: LOG_LEVEL
          value: "INFO"
        - name: LOG_FORMAT
          value: "json"
        - name: METRICS_ENABLED
          value: "true"
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
            nvidia.com/gpu: "1"
          limits:
            memory: "8Gi"
            cpu: "4"
            nvidia.com/gpu: "1"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: model-cache
          mountPath: /root/.cache/huggingface
      volumes:
      - name: model-cache
        persistentVolumeClaim:
          claimName: model-cache-pvc
      nodeSelector:
        nvidia.com/gpu: "true"
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: hamiltonian-monitor
  labels:
    app: hamiltonian-monitor
spec:
  type: LoadBalancer
  selector:
    app: hamiltonian-monitor
  ports:
  - name: api
    port: 80
    targetPort: 8000
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-cache-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
